name: fitness_app_ii_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  fl_chart: ^0.12.1

  video_player: ^1.0.1

  splashscreen: ^1.3.5


flutter:
  uses-material-design: true

  assets:
    - assets/

dev_dependencies:
   flutter_launcher_icons: "^0.8.0"

flutter_icons:
   android: "launcher_icon"
   ios: true
   image_path: "assets/ic_launcher.png"